version: "3"

services:
  ocserv:
    container_name: ocserv
    image: reg.37b.io/pub/ocserv:latest
    build:
      context: .
    ports:
      - "443:443/tcp"
      - "443:443/udp"
    env_file:
      - .env
    volumes:
      - './config/:/config/'
      - './letsencrypt:/etc/letsencrypt'
    cap_add:
      - NET_ADMIN
    privileged: true
    command: ocserv -c /config/ocserv.conf -f --debug=1
    restart: unless-stopped
